# This file was generated by GoReleaser. DO NOT EDIT.
cask "gridctl" do
  name "gridctl"
  desc "MCP orchestration tool - Containerlab for AI Agents"
  homepage "https://github.com/gridctl/gridctl"
  version "0.1.0-alpha.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gridctl"

  on_macos do
    on_intel do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_darwin_amd64.tar.gz"
      sha256 "a242b88f883309e0c699d9bd9516e3521a5945a0f7ab649151ee1b87dcac2472"
    end
    on_arm do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_darwin_arm64.tar.gz"
      sha256 "c49796a72da18017ab4c9481100891f46946d8b5ebdaf79ed171a26205e12588"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_linux_amd64.tar.gz"
      sha256 "f37d576f78d0cb4ace892e81efc68e3988002582e2e0d05e26c5327ec6855a13"
    end
    on_arm do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_linux_arm64.tar.gz"
      sha256 "4ffaacf7024f8ce4277e7fb7a0780a9fe191529f619d242425f89296d579e754"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gridctl"]
  end

  # No zap stanza required
end
