# This file was generated by GoReleaser. DO NOT EDIT.
cask "gridctl" do
  version "0.1.0-beta.6"

  on_macos do
    on_intel do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_darwin_amd64.tar.gz"
      sha256 "2d8757a4a5e70d24470429247ee0c1bfdf5de4a0ffd35fd74e27e89a84051bd9"
    end
    on_arm do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_darwin_arm64.tar.gz"
      sha256 "646e8172c2db3ef8e4926c41a65bbcb082deb84240401c16e73e47fcc9ac08fc"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_linux_amd64.tar.gz"
      sha256 "c63a252f6c2ebd73576f3e8397c61d29f95dd2fea37694d4ed9ffcb2db379a34"
    end
    on_arm do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_linux_arm64.tar.gz"
      sha256 "c2b32aa194a3fe7d3f13f08d6716c0449008e9f6cb018fe0db6551afd9a33204"
    end
  end

  name "gridctl"
  desc "MCP orchestration tool - Containerlab for AI Agents"
  homepage "https://github.com/gridctl/gridctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gridctl"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gridctl"]
  end

  # No zap stanza required

end
