# This file was generated by GoReleaser. DO NOT EDIT.
cask "gridctl" do
  name "gridctl"
  desc "MCP orchestration tool - Containerlab for AI Agents"
  homepage "https://github.com/gridctl/gridctl"
  version "0.1.0-beta.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gridctl"

  on_macos do
    on_intel do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_darwin_amd64.tar.gz"
      sha256 "913bd15d4b94abc6a22560bcd330a8effd06a67877eb1ab037a30b66495d8b8a"
    end
    on_arm do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_darwin_arm64.tar.gz"
      sha256 "b717b431c831699c4422e2e1c3c5569ec3e363756b0d4c8a1afb501ed37c20d5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_linux_amd64.tar.gz"
      sha256 "ac14fade5cfa7f3fa036803efee5ea60719fa1b4652930a0ab8f6abe2366be00"
    end
    on_arm do
      url "https://github.com/gridctl/gridctl/releases/download/v#{version}/gridctl_#{version}_linux_arm64.tar.gz"
      sha256 "c2fc676f2f814ff80ea23ca237713215505102368cf39e10befe8c65fd4f22ab"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gridctl"]
  end

  # No zap stanza required
end
